### ISSUE TITLE
Notification permission

### ISSUE THREAD

**Issue by Sibesaver** [ztNFny/AANotificationForwarder#1]
Unable to Grant permission as it says restricted. Screenshot attached.
![Screenshot_20230512-163645](https://github.com/ztNFny/AANotificationForwarder/assets/41022579/46c6e54b-44d0-4e19-95f0-27dda695e1dd)

**Comment by bggold** [comment]
I used kinginstaller and got it to work.  Might need root.  That installs it like it was from the playstore.

**Comment by Sibesaver** [comment]
Thanks! I might try King installer but not rooting for one trial app.

**Comment by ztNFny** [comment]
What Android version and manufacturer is that?

**Comment by ztNFny** [comment]
This is a limitation in Android 13 for sideloaded apps. You have to explicitly "Allow restricted settings", see e.g. https://droidwin.com/android-13-restricted-settings-for-sideloaded-apps-how-to-bypass/ for a how-to.
I'll add this to the readme.

**Comment by ztNFny** [comment]
Closed by https://github.com/ztNFny/AANotificationForwarder/commit/a2718cc5c9af388d7bba9aeccab662dfc28e6c60
