### ISSUE TITLE
Ignore notification title ignored

### ISSUE THREAD

**Issue by axxxxel** [ztNFny/AANotificationForwarder#10]
I'm trying to forward the speed camera notifications of BLITZER.de to my AA screen. Everything works well but there is probably a problem with the "Ignore notification titles" setting.

BLITZER.de app has a persistent notification that changes icons when GPS signal state is changing. That happens pretty often in tunnels or under long bridges. These notifications always pop up with the title "Dummy - not used".
I thought to add this string to the titles blacklist but they are still popping up.

Is this "Dummy - not used" just set if the notification contains an empty string or something weird? 
The persistent one one shows "App active" and some buttons.

Any recommendation how to remove these empty notifications?

Thanks man, great app!

Notifications in AA:
![PXL_20240221_173227289](https://github.com/ztNFny/AANotificationForwarder/assets/70633435/644b34fb-cafe-49ad-805a-339597ce9005)

**Comment by ztNFny** [comment]
Can you please try with ignore group notifications enabled?

**Comment by ztNFny** [comment]
The string "Dummy - not used" is from this app - but it should never become exposed.
Can you please provide step by steps instructions (screenshots if required) on how to configure the app to trigger those notifications

**Comment by axxxxel** [comment]
All settings are pretty much unchanged.
- Blitzer.de app is selected
- No dismissed notifications
- Ignore titles can be anything
- Ignore group notifications tried both
- rest is unchanged

Maybe you can try it with the speed cam app installed by yourself? There is a free version available:
https://play.google.com/store/apps/details?id=de.blitzer

**Comment by axxxxel** [comment]
Original notification 

![Screenshot_20240221-220044](https://github.com/ztNFny/AANotificationForwarder/assets/70633435/eabae997-3b3f-4a30-b503-1be96c2e37e3)

With AA Notifications (3 changes during App startup)

![Screenshot_20240221-220016](https://github.com/ztNFny/AANotificationForwarder/assets/70633435/ef421211-42ca-429e-94f0-e35e24c59826)

**Comment by ztNFny** [comment]
I'm attaching a new apk with additional logging. Could you please enable debug logging in settings, then capture the log using "adb logcat" on a PC or any of the logcat apps on the PlayStore? The lines I'm looking for contain "xda.xlafbk.aanotificationforwarder"
[app-release.apk.zip](https://github.com/ztNFny/AANotificationForwarder/files/14365160/app-release.apk.zip)

**Comment by axxxxel** [comment]
Now I have created a logcat.log file with grep "xlafbk" fot the time starting up Blitzer.de and receiving the first 3 notifications

[logcat.log](https://github.com/ztNFny/AANotificationForwarder/files/14371045/logcat.log)

**Comment by ztNFny** [comment]
is that with the test-build I attached yesterday? I'm not seeing any of the new debug lines I added

**Comment by axxxxel** [comment]
Yes, that is your special version from yesterday and debugging is active (even though the check box is hidden behind the floating button...)
Maybe the logcat app is removing too much - this is the logcat without grep

[logcat.log](https://github.com/ztNFny/AANotificationForwarder/files/14371135/logcat.log)

**Comment by ztNFny** [comment]
Found it, sorry gave you the wrong advice on how to filter as my logcat output contains slightly different info.

It's as suspected: The notification has no content at all - very "interesting" app design there. I'll try to provide a fix later today.

02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.subText" : "<null>"
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.summaryText" : "<null>"
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.template" : "android.app.Notification$DecoratedCustomViewStyle"
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.text" : "<null>"
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.textLines" : "<null>"
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.title" : "<null>"
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.title.big" : "<null>"
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.verificationText" : "<null>"
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.bigText" : "<null>"
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.infoText" : "<null>"

**Comment by axxxxel** [comment]
Indeed, the app design is kind of wild.
This morning I took two more pictures 
- the first how I like it to be (with speed camera detected)
- second picture is the app notification for an upcoming accident with "Dummy" string again...

![PXL_20240222_061732962](https://github.com/ztNFny/AANotificationForwarder/assets/70633435/56cb5c75-5e84-49ac-9440-78d909fdfd98)

![PXL_20240222_064130463](https://github.com/ztNFny/AANotificationForwarder/assets/70633435/6f971b23-1943-4571-98d2-8a4f4372c6ea)

**Comment by axxxxel** [comment]
Is it maybe possible to check for the existence of a text content (2 min - 500m - A7)?
Otherwise I'm already happy to see the speed cam notifications.

I have recognised the delayed display already this morning. Every speed cam get's 3 alarms (500m, 150m, 50m). 
The 500m warning comes in time but the later ones were delayed until I already passed the cam, but there is an alarm sound.

**Comment by axxxxel** [comment]
Will try - I just need to organize an accident for that...

**Comment by axxxxel** [comment]
On my way home I have recorded a speed cam notification with both title and body not null

[logcat.log](https://github.com/ztNFny/AANotificationForwarder/files/14378043/logcat.log)

![PXL_20240222_165202112](https://github.com/ztNFny/AANotificationForwarder/assets/70633435/64186061-56dc-447e-bedd-9506bc0df020)

**Comment by axxxxel** [comment]
Great, many thanks!
I will perform some trials and provide feedback.
Excellent support 👍
