### ISSUE TITLE
Maxca C5 Pro Android auto for Motorcycle

### ISSUE THREAD

**Issue by RobotsForSTEM** [ztNFny/AANotificationForwarder#11]
Hi.. Thank you for your work..
I was testing your apk with the device in title and notifications are not being forwarded.
The device is detected in your app (AA Connection), Notification Access is Granted but, not even your own Test Notification appears there, although its set in Apps to forward.
Other notifications like whatsApp, for example, are working with that device.
Any idea on workarounds?
Thank you very much and keep up the good work.

**Comment by ztNFny** [comment]
If the test notifications don't work there's no point in trying with other apps. Try reinstalling the app and make sure you allow unknown sources in AA.

**Comment by RobotsForSTEM** [comment]
Hi. Thank you for your answer. In fact, in second installation, it shows already in Android Auto apps and it forwards notifications. Good work. Thank you.

**Comment by RobotsForSTEM** [comment]
Hi. Thank you for your answer. In fact it worked after second install. It shows in Android Auto and notifications are forwarded. Thank you once again. Good work.
