### ISSUE TITLE
Impossible to install 

### ISSUE THREAD

**Issue by Lfpo26** [ztNFny/AANotificationForwarder#12]
Hello,

I have tried to install it via king installer on my huawei p30 with android 11 but it does not work. It says me in French "an error occurs when analyzing the package" whereas unknown sources are activated...
Do you have an idea? 

![Screenshot_20240518_133655_com example kinginstaller](https://github.com/ztNFny/AANotificationForwarder/assets/170179949/c9df9881-6751-462b-850f-cf939cc09e82)
![Screenshot_20240518_133640_com google android packageinstaller](https://github.com/ztNFny/AANotificationForwarder/assets/170179949/67823705-9cc4-4aac-b01f-9a35f686c194)

Thank you

**Comment by ztNFny** [comment]
Most plausible would be a broken download. Verify the file.

md5sum AANotificationForwarder1.4.apk
87f28f3d03e4fee6e2fafd1af315a147  AANotificationForwarder1.4.apk

sha512sum AANotificationForwarder1.4.apk
2ec3d941298d1358a1a1a6351c5e44635bb639277e2cddcc6e119d1cab65d1951f5147e6f5d2f173dd2094e01fa850dda0ef26d3bae442e651d9292fae4f9fdd  AANotificationForwarder1.4.apk

**Comment by ztNFny** [comment]
No feedback after months, closing
