### ISSUE TITLE
Two notifications 

### ISSUE THREAD

**Issue by bggold** [ztNFny/AANotificationForwarder#2]
I'm getting two of every notification for the app posting it.  I know there is a notification from this app.

Nice job on the rewrite and functionality for newer AA.

This was originally my idea for emil.  If you need any help let me know.

Thanks

**Comment by ztNFny** [comment]
Are you able to add any details to your report? E.g. which app is causing this. I've yet to see a doubled notification.
Even if an app sends the same notification twice (as my mail client does) this is filtered out.

You're very welcome to contribute!

**Comment by bggold** [comment]
It is on every app.  Not sure if it might be related to the android auto settings for messages or not.

**Comment by ztNFny** [comment]
"every app" is simply wrong. Without knowing which app to check i can't look into this. It's not happening for any of the apps I tested.

**Comment by bggold** [comment]
Not trying to make it difficult for you.  If there was logging I could send
I would.

Also I uninstalled and reinstalled the app.  I followed the android 13
directions and I have no overflow button to enable restricted.

I originally had to install with kinginstaller.  I thought that might have
been the issue.

I am not a developer so not sure what else.

Pixel 7 pro a13 rooted.

Outlook and Gmail to start.

But all apps are doing it.

**Comment by bggold** [comment]
Ok got restricted access now.  Will test again shortly.

**Comment by ztNFny** [comment]
> Outlook and Gmail to start.

Well that wasn't so hard 😜 Gmails notifications are known to cause problems in all kind of listener scenarios. Try "Ignore Group Summary Notifications" setting in 1.1

**Comment by bggold** [comment]
Thanks for the quick update.  So far that seems to have fixed the mail
client issues.  I will let you know on other apps.

**Comment by bggold** [comment]
All apps working as expected with the new settings option.

Thanks
