### ISSUE TITLE
No notifications at all

### ISSUE THREAD

**Issue by Dehumanizer77** [ztNFny/AANotificationForwarder#6]
Hi,

I just started to have a problem that no notifications are sent to android auto, not from the original carnotifier and not from your forked version. I don't know if it was caused by some recent update, I remember having notifications just a few days ago and I have tried to downgrade to AA versions released in June (9.7 - 9.8), but it didn't help. I have then also tried to upgrade to the latest daily version (10.1.132904) but still no notifications. Not even in the notifications drawer of AA. Some time ago there were some AA versions that did not show the notification popup, but the notifications were there if you went to the notifications section, but now it's completely empty. However on the phone I see these notifications from your app, so the problem is that AA doesn't pick it up for some reason.
I have Android 12 (Pixel Experience ROM)
I also had the similar problem (no notifications) before I have realised I have to enable car mode when connected to AA, then I have automated it by Automate so that it turns on automatically. I have tried to enable/disable it manually but it also didn't help.

Do you have any idea on what might be wrong? I'm desperate here... It was perfectly working just a few days ago and now nothing.

**Comment by ztNFny** [comment]
Does the test notification work? If not you probably disabled notification in AAs settings.

**Comment by Dehumanizer77** [comment]
OK I have just found out the problem. The problem is that there are notification settings in at least three different places. If I had an android developer responsible for this near me right now, they would end up really bad for stealing several hours of my time when I was desperately debugging what could possibly be wrong.
The setting that made the notifications not work is at Settings->Notifications->Device & App notifications->Android Auto and there, for some unknown reason I had "notifications" checkbox unset, while all others were set, so regular conversations notifications were going through fine... Grrr
I have no idea why the setting was turned off, I certainly did not turn it off myself.
