### ISSUE TITLE
Notifications suggestion

### ISSUE THREAD

**Issue by Dehumanizer77** [ztNFny/AANotificationForwarder#7]
First off, thank you very much for working on this, I really appreciate it, as this is an essential stuff for me :-)

So, to the point, I see that you have rewritten the original carnotifier in the way that the notification shows up as a regular conversation message in AA, so in the split view, it stays visible until you dismiss it manually. Which is cool for some apps, but for some others I prefer the way how the original carnotifier handled it, i.e. I just get a popup and then it disappears and just stays in the notifications drawer (and I can read it if I go to notifications section).
That said, would it be possible to have both of these types of notifications and a possibility to change which type to use for each application in the settings?

**Comment by Dehumanizer77** [comment]
Ok it seems I didn't check the settings of the app well, the "apps to dismiss original notification" setting does exactly what I was talking about, is that right?
I will test it tomorrow, as I'm not near the car anymore.

**Comment by ztNFny** [comment]
There is only 1 kind of notification that AA shows. All notifications are displayed on the main screen as overlay, then dismissed after a few seconds and can later be accessed from notifications view.
No need to dismiss any "popup" manually

**Comment by Dehumanizer77** [comment]
That's not true, with the new split design, the notifications stay on the main screen until dismissed.
This is the original carnotifier overlay notification:
![1](https://github.com/ztNFny/AANotificationForwarder/assets/1876451/488a61b4-8321-40f9-bd7c-374840727e30)
This is the same notification from your app:
![2](https://github.com/ztNFny/AANotificationForwarder/assets/1876451/f68f8e7a-9c34-4cac-97f8-b491e6722c83)
And this is how it looks like after a few seconds with your app:
![3](https://github.com/ztNFny/AANotificationForwarder/assets/1876451/b0a2f2f1-51a0-4bc6-b8f4-c4309af66f48)

There is no notification from carnotifier on the main screen after the initial overlay.

**Comment by ztNFny** [comment]
The "notifications without actions" have been deprecated for a very long time now. I'm surprised they still work for you, they've been non-functional for about a year with my devices. Thus I'll not implemented the "legacy" way.

The notification area on the top right is also dismissed after some time, not sure about the interval, I'd say about 5 minutes.

**Comment by Dehumanizer77** [comment]
oh ok, makes sense, thank you.
