### ISSUE TITLE
AA 11.2.640404 breaks notifications 

### ISSUE THREAD

**Issue by bggold** [ztNFny/AANotificationForwarder#8]
Looks like with the latest AA 11.2.64.0404 it breaks notifications on the head unit.  Have been running this app for over 8 months and no issues until now.

**Comment by ztNFny** [comment]
I'm unable to reproduce any issues. I tested with 11.2.640404 arm64 on my real device against my car and 11.2.640404 x64 with emulator and desktop-head-unit, both are working fine.

**Comment by bggold** [comment]
Can you tell anything from the logcat?   It was working up until the latest update.  Not sure if the new AI setting has anything to do with it now.  I have disabled it too.

Thanks
![part-0](https://github.com/ztNFny/AANotificationForwarder/assets/34557165/71e1085f-3141-486e-91fc-a8e6368ea284)

[log.txt](https://github.com/ztNFny/AANotificationForwarder/files/14087672/log.txt)

**Comment by ztNFny** [comment]
I don't have those auto-play and AI options. Guess those are controlled server-side as with many of AAs features.

**Comment by bggold** [comment]
I guess once you get them we will know if that's the issue or not.

Thanks

**Comment by fwon2638** [comment]
> Looks like with the latest AA 11.2.64.0404 it breaks notifications on the head unit. Have been running this app for over 8 months and no issues until now.

I have the same problem.

**Comment by ztNFny** [comment]
Still no AI options here, still working.
Disabling the AI summary option doesn't help I guess? Can you try reinstalling from scratch, following all the steps? There was someone on XDA for whom it stopped working, then after reinstall with re-enabling unknown sources it worked again.

**Comment by fwon2638** [comment]
> Still no AI options here, still working. Disabling the AI summary option doesn't help I guess? Can you try reinstalling from scratch, following all the steps? There was someone on XDA for whom it stopped working, then after reinstall with re-enabling unknown sources it worked again.

Not working. I have downgraded AA to a much earlier version and your app works again. Guess, I will not updated AA for the time being.

**Comment by fwon2638** [comment]
> Looks like with the latest AA 11.2.64.0404 it breaks notifications on the head unit. Have been running this app for over 8 months and no issues until now.

Do you still have the issue?

**Comment by fwon2638** [comment]
> > Looks like with the latest AA 11.2.64.0404 it breaks notifications on the head unit. Have been running this app for over 8 months and no issues until now.
> 
> Do you still have the issue?

It is working now. My AA version is 11.4 +

**Comment by bggold** [comment]
> > > Looks like with the latest AA 11.2.64.0404 it breaks notifications on the head unit. Have been running this app for over 8 months and no issues until now.
> > 
> > Do you still have the issue?
> 
> It is working now. My AA version is 11.4 +

What did you do besides upgrade to 11.4?  I am on 11.4 and it still is not working.

**Comment by ztNFny** [comment]
I'm on 11.3, have the AI settings now, but it's still working fine...

If you still issues please update to 1.4 (it won't fix your issues as there are no changes in the relevant code), enable debug logging in the apps options and share the adb logcat (use PC or an app to get it) of receiving a notification that you'd expect to be forwarded, should look like this:
02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.subText" : ""

Do the test notifications work for you?

**Comment by bggold** [comment]
> I'm on 11.3, have the AI settings now, but it's still working fine...
> 
> If you still issues please update to 1.4 (it won't fix your issues as there are no changes in the relevant code), enable debug logging in the apps options and share the adb logcat (use PC or an app to get it) of receiving a notification that you'd expect to be forwarded, should look like this: 02-22 09:18:45.681 D/AANotificationForwarder(30338): Bundle content - "android.subText" : ""
> 
> Do the test notifications work for you?
[log.txt](https://github.com/ztNFny/AANotificationForwarder/files/14450570/log.txt)


Test Notifications do not work.  Here is a log.  Let me know if there is anything you need.

**Comment by ztNFny** [comment]
The test notification does show on your phone, just not in AA? I don't see any reason for that to happen. My only idea would be to clear settings for AA and Play Services, uninstall this app and set up everything from scratch.

**Comment by bggold** [comment]
> The test notification does show on your phone, just not in AA? I don't see any reason for that to happen. My only idea would be to clear settings for AA and Play Services, uninstall this app and set up everything from scratch.

Shows up on phone not AA.

**Comment by bggold** [comment]
> The test notification does show on your phone, just not in AA? I don't see any reason for that to happen. My only idea would be to clear settings for AA and Play Services, uninstall this app and set up everything from scratch.

Well crap that did the trick.  I cleared cache and data on AA and that did the trick.  Thanks

**Comment by bggold** [comment]
Well crap that did the trick. I cleared cache and data on AA and that did the trick. Thanks
